# SPDX-FileCopyrightText: 2021 Tzu-Hao Kuo
#
# SPDX-License-Identifier: GPL-3.0-or-later

list_f: 'data/samples.10.rna_full.tsv'
out_table: 'rpg.txt'
out_log_table: 'rpg.log.txt'
ref_fasta: 'Pseudomonas_aeruginosa_PA14.edit.fasta'
annot_tab: 'Pseudomonas_aeruginosa_PA14_annotation_with_ncRNAs_07_2011_12genes.tab'
r_annot: 'Pseudomonas_aeruginosa_PA14_12genes_R_annotation'
