# SPDX-FileCopyrightText: 2021 Tzu-Hao Kuo
#
# SPDX-License-Identifier: GPL-3.0-or-later

list_f: 'data/samples.10.dna_full.with_ref.tsv'
out_prokka_dir: 'prokka'
out_roary_dir: 'roary'
extracted_proteins_dir: 'extracted_proteins_nt/'
out_gpa_f: 'annot.mat'
out_indel_f: 'indel_annot.mat'
REF_GFF: '/net/metagenomics/data/from_moni/old.tzuhao/seq2geno/dev_versions/v9/.ori_backup/gpa/match_reference_annotation/RefCln_UCBPP-PA14.gff'
anno_f: '.ori_backup/Pseudomonas_aeruginosa_PA14_annotation_with_ncRNAs_07_2011_12genes.tab'
